

yaku_map_eng = {
    34: 'Daburu riichi',
    19: 'Dai sangen',
    21: 'Dai suushii',
    25: 'Junchan',
    9: 'Iipeikou',
    35: 'Ippatsu',
    12: 'Itsu',
    32: 'Kokushi musou',
    36: 'Menzen tsumo',
    8: 'Pinfu',
    43: 'Renhou',
    33: 'Riichi',
    38: 'Rinshan kaihou',
    30: 'Ryuu iisou',
    10: 'Ryan peikou',
    3: 'San ankou',
    5: 'San kantsu',
    11: 'Sanshoku',
    4: 'Sanshoku dokou',
    7: 'Suu ankou',
    6: 'Suu kantsu',
    23: 'Tanyao',
    39: 'Tenhou',
    1: 'Toi-toi',
    37: 'Haitei',
    27: 'Honitsu',
    2: 'Honroutou',
    41: 'Houtei',
    22: 'Tsuu iisou',
    42: 'Chan kan',
    24: 'Chanta',
    31: 'Chiitoitsu',
    28: 'Chinitsu',
    26: 'Chinroutou',
    40: 'Chihou',
    29: 'Chuuren pooto',
    18: 'Shou sangen',
    20: 'Shou suushii',
    13: 'Yakuhai x1',
    14: 'Yakuhai x2',
    15: 'Yakuhai x3',
    16: 'Yakuhai x4',
    17: 'Yakuhai x5',
    44: 'Open riichi',
    45: 'Yakuhai: all'
}

yaku_map_short = {
    34: 'daburu_riichi',
    19: 'daisangen',
    21: 'daisuushii',
    25: 'junchan',
    9: 'iipeikou',
    35: 'ippatsu',
    12: 'itsu',
    32: 'kokushi_musou',
    36: 'tsumo',
    8: 'pinfu',
    43: 'renhou',
    33: 'riichi',
    38: 'rinshan_kaihou',
    30: 'ryuu_iisou',
    10: 'ryanpeikou',
    3: 'sanankou',
    5: 'sankantsu',
    11: 'sanshoku',
    4: 'sanshoku_dokou',
    7: 'suuankou',
    6: 'suukantsu',
    23: 'tanyao',
    39: 'tenhou',
    1: 'toitoi',
    37: 'haitei',
    27: 'honitsu',
    2: 'honroutou',
    41: 'houtei',
    22: 'tsuuiisou',
    42: 'chankan',
    24: 'chanta',
    31: 'chiitoitsu',
    28: 'chinitsu',
    26: 'chinroutou',
    40: 'chihou',
    29: 'chuurenpooto',
    18: 'shousangen',
    20: 'shousuushii',
    13: 'yakuhai1',
    14: 'yakuhai2',
    15: 'yakuhai3',
    16: 'yakuhai4',
    17: 'yakuhai5',
    44: 'open_riichi',
    45: 'yakuhai_all'
}

yaku_eng_rus = {
    'Daburu riichi': 'Дабл риичи',
    'Dai sangen': 'Дайсанген',
    'Dai suushii': 'Дайсуши',
    'Junchan': 'Джунчан',
    'Iipeikou': 'Иипейко',
    'Ippatsu': 'Иппацу',
    'Itsu': 'Иццу',
    'Kokushi musou': 'Кокуши мусо',
    'Menzen tsumo': 'Мендзен цумо',
    'Pinfu': 'Пин-фу',
    'Renhou': 'Ренхо',
    'Riichi': 'Риичи',
    'Rinshan kaihou': 'Риншан кайхо',
    'Ryuu iisou': 'Рюисо',
    'Ryan peikou': 'Рянпейко',
    'San ankou': 'Сананко',
    'San kantsu': 'Санканцу',
    'Sanshoku': 'Саншоку',
    'Sanshoku dokou': 'Саншоку доко',
    'Suu ankou': 'Сууанко',
    'Suu kantsu': 'Сууканцу',
    'Tanyao': 'Таняо',
    'Tenhou': 'Тенхо',
    'Toi-toi': 'Тойтой',
    'Haitei': 'Хайтей',
    'Honitsu': 'Хоницу',
    'Honroutou': 'Хонрото',
    'Houtei': 'Хотей',
    'Tsuu iisou': 'Цуисо',
    'Chan kan': 'Чанкан',
    'Chanta': 'Чанта',
    'Chiitoitsu': 'Чиитойцу',
    'Chinitsu': 'Чиницу',
    'Chinroutou': 'Чинрото',
    'Chihou': 'Чихо',
    'Chuuren pooto': 'Чууренпото',
    'Shou sangen': 'Шосанген',
    'Shou suushii': 'Шосуши',
    'Yakuhai x1': 'Якухай 1',
    'Yakuhai x2': 'Якухай 2',
    'Yakuhai x3': 'Якухай 3',
    'Yakuhai x4': 'Якухай 4',
    'Yakuhai x5': 'Якухай 5',
    'Open riichi': 'Опен риичи',
    'Yakuhai: all': 'Якухай: всего'
}

yaku_map_rus = {
    34: 'Дабл риичи',
    19: 'Дайсанген',
    21: 'Дайсуши',
    25: 'Джунчан',
    9: 'Иипейко',
    35: 'Иппацу',
    12: 'Иццу',
    32: 'Кокуши мусо',
    36: 'Мендзен цумо',
    8: 'Пин-фу',
    43: 'Ренхо',
    33: 'Риичи',
    38: 'Риншан кайхо',
    30: 'Рюисо',
    10: 'Рянпейко',
    3: 'Сананко',
    5: 'Санканцу',
    11: 'Саншоку',
    4: 'Саншоку доко',
    7: 'Сууанко',
    6: 'Сууканцу',
    23: 'Таняо',
    39: 'Тенхо',
    1: 'Тойтой',
    37: 'Хайтей',
    27: 'Хоницу',
    2: 'Хонрото',
    41: 'Хотей',
    22: 'Цуисо',
    42: 'Чанкан',
    24: 'Чанта',
    31: 'Чиитойцу',
    28: 'Чиницу',
    26: 'Чинрото',
    40: 'Чихо',
    29: 'Чууренпото',
    18: 'Шосанген',
    20: 'Шосуши',
    13: 'Якухай 1',
    14: 'Якухай 2',
    15: 'Якухай 3',
    16: 'Якухай 4',
    17: 'Якухай 5',
    44: 'Опен риичи',
    45: 'Якухай: всего'
}

yaku_short_rus = {
    'daburu_riichi': 'Дабл риичи',
    'daisangen': 'Дайсанген',
    'daisuushii': 'Дайсуши',
    'junchan': 'Джунчан',
    'iipeikou': 'Иипейко',
    'ippatsu': 'Иппацу',
    'itsu': 'Иццу',
    'kokushi_musou': 'Кокуши мусо',
    'tsumo': 'Мендзен цумо',
    'pinfu': 'Пин-фу',
    'renhou': 'Ренхо',
    'riichi': 'Риичи',
    'rinshan_kaihou': 'Риншан кайхо',
    'ryuu_iisou': 'Рюисо',
    'ryanpeikou': 'Рянпейко',
    'sanankou': 'Сананко',
    'sankantsu': 'Санканцу',
    'sanshoku': 'Саншоку',
    'sanshoku_dokou': 'Саншоку доко',
    'suuankou': 'Сууанко',
    'suukantsu': 'Сууканцу',
    'tanyao': 'Таняо',
    'tenhou': 'Тенхо',
    'toitoi': 'Тойтой',
    'haitei': 'Хайтей',
    'honitsu': 'Хоницу',
    'honroutou': 'Хонрото',
    'houtei': 'Хотей',
    'tsuuiisou': 'Цуисо',
    'chankan': 'Чанкан',
    'chanta': 'Чанта',
    'chiitoitsu': 'Чиитойцу',
    'chinitsu': 'Чиницу',
    'chinroutou': 'Чинрото',
    'chihou': 'Чихо',
    'chuurenpooto': 'Чууренпото',
    'shousangen': 'Шосанген',
    'shousuushii': 'Шосуши',
    'yakuhai1': 'Якухай 1',
    'yakuhai2': 'Якухай 2',
    'yakuhai3': 'Якухай 3',
    'yakuhai4': 'Якухай 4',
    'yakuhai5': 'Якухай 5',
    'open_riichi': 'Опен риичи',
    'yakuhai_all': 'Якухай: всего'
}